services:
  django_blog_mariadb:
    container_name: django_blog_mariadb
    image: mariadb:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MARIADB_USER: maindb
      MARIADB_PASSWORD: secret
      MARIADB_DATABASE: maindb
      MARIADB_ROOT_PASSWORD: megasec
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - ./mysql:/var/lib/mysql