# Generated by Django 5.1 on 2024-08-21 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("django_blog_backend", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blogsettings",
            old_name="blog_default_language",
            new_name="default_language",
        ),
        migrations.RenameField(
            model_name="blogsettings",
            old_name="blog_description",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="blogsettings",
            old_name="blog_title",
            new_name="title",
        ),
    ]
