# Generated by Django 5.1 on 2024-08-22 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "django_blog_backend",
            "0002_rename_blog_default_language_blogsettings_default_language_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("value", models.TextField()),
                (
                    "blog_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_blog_backend.blogsettings",
                    ),
                ),
            ],
        ),
    ]
